# Generated by Django 3.0.7 on 2020-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='section',
            field=models.ManyToManyField(blank=True, to='account.Section', verbose_name='セクション'),
        ),
    ]
