# Generated by Django 3.1.1 on 2020-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200620_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='duties',
            field=models.CharField(choices=[('1', 'リーダー'), ('2', 'ベテラン'), ('3', '新人')], default='3', max_length=1, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], default='1', max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='顔写真'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
    ]
