# Generated by Django 3.1.1 on 2020-09-17 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='description',
        ),
        migrations.AlterField(
            model_name='shift',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='終日'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_work',
            field=models.BooleanField(default=False, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
